### ISSUE TITLE
Slightly simpler ESM

### ISSUE THREAD

**Issue by WebReflection** [felixfbecker/node-sql-template-strings#102]
I'll write this down so you can eventually consider it, evaluate it, ignore it, throw it away, or insult me, if you feel like that.

This is a slightly simplification of the current file, for ESM.

  * less moving parts (no runtime fields added, such `name` or `bind`, and nothing is deleted. V8 is very fast with these kind of objects as long as `delete` is not used, and runtime properties are not assigned.
  * no need for the class. `typeof` is faster, and the signature already guard against strings or expected objects that could be just an interface, at this point
  * easier, scoped, strings and values access, removing the need to look for the right array to modify

Best Regards

```js
export const SQL = (tpl, ...values) => {
  const strings = tpl.slice(0)
  return {

    // Accessors

    get bind() {
      return this.bound ? values : void 0
    },

    /** Returns the SQL Statement for Sequelize */
    get query() {
      return this.bound ? this.text : this.sql
    },
    
    get sql() {
      return strings.join('?')
    },

    /** Returns the SQL Statement for node-postgres */
    get text() {
      return strings.reduce((p, c, i) => `${p}$${i}${c}`)
    },

    get values() {
      return this.bound ? void 0 : values
    },


    // Methods

    /**
     * @param {SQLStatement|string} statement
     * @returns {this}
     */
    append(statement) {
      if (typeof statement === 'string')
        strings[strings.length - 1] += statement
      else {
        strings[strings.length - 1] += statement.strings[0]
        strings.push(...statement.strings.slice(1))
        values.push(...statement.values)
      }
      return this
    },

    /**
     * @param {string} name
     * @returns {this}
     */
    setName(name) {
      this.name = name
      return this
    },

    /**
     * Use a prepared statement with Sequelize.
     * Makes `query` return a query with `$n` syntax instead of `?`  and uses `bind` instead of `values`
     * @param {boolean} [bound=true] bound If omitted, defaults to `true`
     * @returns this
     */
    useBind(bound = true) {
      this.bound = bound
      return this
    },


    // Properties

    /** Default bound value as false */
    bound: false,

    /** Default name as empty string */
    name: '',

    /** Initial strings */
    strings
  }
}

export default SQL
```

**Comment by felixfbecker** [comment]
Did you test this? It would make more sense to submit a PR so we can have CI run over it and see if all tests still pass.

**Comment by WebReflection** [comment]
I wanted to know if you'd be happy, since it's some refactoring and there's no exported class anymore.

GitHub also swallows the double `$` in the reduce, there should be a `$$i` instead of `$i`.

I can try to test it whenever I have time and see how it goes. If it works, would you be OK with the MR?

Regards

**Comment by felixfbecker** [comment]
I am not confident that this actually works yet so I can't promise you that it will be merged. Just submit a PR and when CI passes I can review it. Commenting on an issue is not an efficient way to comment on code.

**Comment by WebReflection** [comment]
All green, and coverage 100% https://github.com/felixfbecker/node-sql-template-strings/pull/103

**Comment by WebReflection** [comment]
OK, I'll close this since it's not moving and it won't bring much improvements on the real-world.
