### ISSUE TITLE
how to handle parameters of dynamic length?

### ISSUE THREAD

**Issue by lalitkapoor** [felixfbecker/node-sql-template-strings#21]
how do you deal with a dynamic number of parameters? E.g. in the following query you want to pass in an array of ids of dynamic length.

```SQL
SELECT * 
FROM users 
WHERE id IN (1, 2, 3, 4, 5, ...)
```

Thanks!

**Comment by lalitkapoor** [comment]
please check out #22 Thanks!

**Comment by felixfbecker** [comment]
Use Postgres `ANY`:
```js
const ids = [1, 2, 3]
db.query(SQL`SELECT * FROM users WHERE id = ANY(${ids})`)
```
Using `IN` for prepared statements is very bad because the query itself now depends on the values. This means you cannot just prepare it once and execute which different values later, you need to re-prepare every time your array changes.

**Comment by lalitkapoor** [comment]
Hey @felixfbecker - I appreciate the feedback!

For clarification, using IN wouldn't negative impact a parameterized query right? Only a prepared statement? (Asking in the context of PostgreSQL)

https://github.com/brianc/node-postgres/wiki/Parameterized-queries-and-Prepared-Statements


You can disregard my pull request, will close that, as it's not friendly with ANY.

Thanks for the quick response!

**Comment by felixfbecker** [comment]
Not sure, but I don't think so. I don't know though whether pg supports flattening out parameters, since ANY solves this in a much nicer way.

And yeah, flattening out the values would not work in cases where you want to insert an actual array. Appreciate your contribution though.
