### ISSUE TITLE
error with typescript

### ISSUE THREAD

**Issue by abenhamdine** [felixfbecker/node-sql-template-strings#23]
Hello Felix, and thx for this very useful module.

I'm currently migrating a project on Typescript (version 2.1.4) and I'm running into a type error

```js
import sqlTemplate = require('sql-template-strings');

var foo: number = 1;

const sql = sqlTemplate`  SELECT
                            pay_etablissement_eta.eta_id
                        FROM
                            pay_etablissement_eta
                        WHERE
                            pay_etablissement_eta.pad_id = ${foo}
                        LIMIT 1;`;
```

produces the following error : 

![image](https://cloud.githubusercontent.com/assets/7466144/21079488/2a995740-bf93-11e6-9253-22e33587fff4.png)

Do you understand the rationale of this error ?
Any idea to fix it ?

Thx by advance.

FWIW, my ts compile options : 
```json
"compilerOptions": {
        "removeComments": true,
        "compileOnSave": true,
        "sourceMap": false,
        "moduleResolution": "node",
        "pretty": true,
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": false,
        "strictNullChecks": true,
        "watch": true
    },
```

**Comment by felixfbecker** [comment]
In TypeScript, you should use
```ts
import SQL from 'sql-template-strings'
```

**Comment by abenhamdine** [comment]
Ah thx a lot. It's sometimes difficult for a newcomer to typescript to sort out all the different export/import patterns...

**Comment by felixfbecker** [comment]
The definition file can tell you: https://github.com/felixfbecker/node-sql-template-strings/blob/master/index.d.ts#L76

**Comment by abenhamdine** [comment]
ah thx again !
I think I get it now.
