### ISSUE TITLE
How to use with batch insert queries?

### ISSUE THREAD

**Issue by rightaway** [felixfbecker/node-sql-template-strings#24]
How could this be used with batch insert queries? For example if I want to do

```sql
insert into mytable(a,b,c) values (1,2,3), (4,5,6), (7,8,9)
```
How would I use sql-template-strings in this code to make it work? Or is it not possible/recommended to use with batch queries like this?
```js
const rows = [
  { a: 1, b: 2, c: 3 },
  { a: 4, b: 5, c: 6 },
  { a: 7, b: 8, c: 9 },
]
insert(rows)

function insert(rows) {
  let query = `insert into mytable (a,b,c) values `
  for (const row of rows) {
   query +=   // Can sql-template-strings be used here?
  }
}
```

**Comment by felixfbecker** [comment]
You can use `.append()`, but be aware that you shouldn't do this with prepared statements.

**Comment by rightaway** [comment]
It's never a prepared statement by default right? (Unless `.setName` is called?)

**Comment by felixfbecker** [comment]
What dialect and driver are you using?

**Comment by rightaway** [comment]
Dialect is postgres. I'm using https://www.npmjs.com/package/pg, is that the driver?

**Comment by felixfbecker** [comment]
Yes. In that case it's only a prepared statements if you do `setName()`.
