### ISSUE TITLE
Trailing comma

### ISSUE THREAD

**Issue by rightaway** [felixfbecker/node-sql-template-strings#25]
I'm having a problem with trailing commas, is there a way that this module can handle that?

```js
function insert(rows) {
  let query = sql`insert into mytable (a,b,c) values `
  for (const row of rows) {
   query.append(sql`(${row.a}, ${row.b}, ${row.c}), `)
  }
}
```

But then there's an error `error: syntax error at end of input`. Is there a simple way to get rid of the last comma at the end of the whole query? I see only a `.append` but nothing to remove some characters.

**Comment by felixfbecker** [comment]
I would use reduce() or map() and join() instead of for..of

**Comment by rightaway** [comment]
I don't see to be doing it right. If I do

```js
    const query = sql`insert into mytable (a,b,c) values `
    query.append(rows.map(row => sql`(${row.a}, ${row.b}, ${row.c}`).join(', '))
    console.log(query)
```

The output is

```sql
SQLStatement {
  strings: [ 'insert into mytable (a,b,c) values [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], ......
  values: [] }
```

Do you know what I'm doing wrong?

**Comment by felixfbecker** [comment]
okay, looks like I was wrong about that. I don't think it is possible without special-treating one element, for example
```js
function insert(rows) {
  let query = sql`insert into mytable (a,b,c) values `
  for (const [i, row] of rows.entries()) {
   if (i > 0) query.append(', ')
   query.append(sql`(${row.a}, ${row.b}, ${row.c})`)
  }
}
```
