### ISSUE TITLE
Add npm install code block to readme

### ISSUE THREAD

**Issue by coreylight** [felixfbecker/node-sql-template-strings#26]
Had to look up what the actual lib name was for npm. This might make it a little easier!
Thank you for the lib!

**Comment by coreylight** [comment]
I'm silly and overlooked the `require` block. Might still help but would prob be redundant. 😜

**Comment by felixfbecker** [comment]
There are also 3 npm badges that link to the package on npm.

**Comment by allthesignals** [comment]
I agree this should be in the README - yes, the require block and npm badges are there, but it's pretty common across thousands of repos to just have the install snippet. I just like to feel like I'm installing the right thing.

(Also, I love this package - thank you!)
