### ISSUE TITLE
Make property strings public

### ISSUE THREAD

**Issue by abenhamdine** [felixfbecker/node-sql-template-strings#28]
Hi and thx a lot for this great & tiny module !

In our project, we used to use this module to build sql queries dynamically, and we access property `strings` to do this, eg with stuff like : 
```ts
sql.strings[sql.strings.length - 1] = _.trimEnd(sql.strings[sql.strings.length - 1], " UNION ");
```

However, since `strings` is currently marked as private, we get a ts error.

Would it be possible to make `strings` public ?
In https://github.com/felixfbecker/node-sql-template-strings/blob/master/index.d.ts#L4  
 (or in https://github.com/felixfbecker/node-sql-template-strings/pull/11/files#diff-f41e9d04a45c83f3b6f6e630f10117feR40 if it's merged)

IMHO there's no risk for users to make this property public.

**Comment by felixfbecker** [comment]
`strings` is supposed to be internal - that is very important because the length of `strings` needs to match the length of `values` so that it's always
`string ${value} string ${value} string`
(even if the last part is an empty string)
You should use `append()` to extend the query.
