### ISSUE TITLE
Dialect selection rather than both mysql & postgres

### ISSUE THREAD

**Issue by fritzy** [felixfbecker/node-sql-template-strings#3]
Knex does it like this:

```js
let knex = require('knex')({dialect: 'pg'})
```

I could see having a .PG and .MySQL object, and sharing code where possible, or having a constructor like knex with a dialect option.

**Comment by felixfbecker** [comment]
Hmmmm. You must admit "it just works" is kind of cool aswell. The point is to avoid all the configuration knex requires. What do you think about `SQL.setDialect('mysql')`? Example:
```js
let SQL = require('sql-template-strings') // will work in hybrid mode
let SQL = require('sql-template-strings').setDialect('mysql') // sets dialect to mysql and returns this
```

**Comment by fritzy** [comment]
makes sense to me.
