### ISSUE TITLE
Lack of tests & docs regarding SQL injection vulnerabilities

### ISSUE THREAD

**Issue by ewindisch** [felixfbecker/node-sql-template-strings#33]
The reason that parametrized queries exist are to avoid the SQL injections that are inevitable from parsing strings. This project appears to simply attempt to circumvent that security mechanism (even if it does not, ultimately). How this deals with SQL injections should be documented. Tests should cover SQL injections as well.

**Comment by felixfbecker** [comment]
Could you please explain in detail how this project circumvents that mechanism?

**Comment by felixfbecker** [comment]
This project does not do any text parsing, it just takes the strings and values and packs them in an object as described here: https://github.com/felixfbecker/node-sql-template-strings#how-it-works.
Any specific improvements you would do to the documentation?
