### ISSUE TITLE
Handle SQL IN(...) statement

### ISSUE THREAD

**Issue by benomite** [felixfbecker/node-sql-template-strings#42]
Just submitting an enhancement idea.
It would be awesome if this could work:

``` javascript
query.append(SQL` WHERE i.type IN (${types})`);
```
This results in an error `error: invalid input syntax for integer: "4,2,3"`

For now, the workaround is something like:
``` javascript
query.append(`
  WHERE i.type IN (
`);
types.forEach((id, index, type) => {
    where.append(SQL`${id}`);
    if(index < types.length - 1) {
      where.append(',');
    }
});
where.append(`)`);
```

Thanks for this awesome module !

**Comment by felixfbecker** [comment]
See https://github.com/felixfbecker/node-sql-template-strings/issues/34#issuecomment-292319942

**Comment by felixfbecker** [comment]
If you use a dialect that doesn't support `ANY`, you can also write it like this:
```ts
types.reduce((id, index) => where.append(SQL`${id}`).append(index < types.length - 1 ? ',' : ''));
```

**Comment by felixfbecker** [comment]
It is probably worth to add some documentation for this

**Comment by benomite** [comment]
Thank you very much! Exactely what I needed.
I'll try to find time for a PR and add these info in the readme.

**Comment by benomite** [comment]
https://github.com/felixfbecker/node-sql-template-strings/pull/43

**Comment by ro-savage** [comment]
@felixfbecker - Unless I am missing something your suggest doesn't work as it append a `,` to the start of the where clause.
e.g. `query SELECT * FROM transactions WHERE id IN (,$1,$2)`

Could a helper be made, something like `.appendWhereIn(columnName, array)` that takes an array and then creates the correct where clause for you?

```
function appendWhereIn(column, array) {
  this.query.append(`
      WHERE txHash IN (
    `);
    transactions.forEach((transaction, i) => {
      this.query.append(SQL`${transaction}`)
      if (i < transactions.length - 1) { query.append(',') }
    })
    this.query.append(`)`)
}

**Comment by ro-savage** [comment]
The reason for creating a new function, is to give users insight into how to use this module.

Its no obvious for someone new that they can not do this
```
SQL`SELECT * FROM transactions WHERE id IN (${transactions.join(', ')})`
```

Then they have to run down a huge rabbit hole of trying to figure out the correct way to do this.

While having a specific function, and docs they explain it saves people from going through the same process over and over.

We ended up using

```js
SQL.SQLStatement.prototype.appendWhereIn = function (column, array) {
  this.append(` WHERE ${column} IN (`);
  array.forEach((item, i) => {
    this.append(SQL`${item}`)
    if (i < array.length - 1) { this.append(',') }
  })
  this.append(`)`)

  return this
}
```
