### ISSUE TITLE
Syntax highlighting for Sublime Text

### ISSUE THREAD

**Issue by Amoki** [felixfbecker/node-sql-template-strings#50]
I heavily use SQL-Template-Strings in my code and the lack of SQL syntax highlighting bothered me.
I created a sublime-syntax derived from the default Sublime JS syntax that allow SQL highlighting.

![image](https://user-images.githubusercontent.com/1349751/29559099-66d92074-872e-11e7-8e3b-ef4894d674bf.png)

You can find it here: [javascript-sql-sublime-syntax](https://github.com/AsterisqueDigital/javascript-sql-sublime-syntax)

**Comment by felixfbecker** [comment]
Want to add this to the readme?

**Comment by Amoki** [comment]
Sorry for the delay but feel free to do it !
