### ISSUE TITLE
docs home page is confusing?

### ISSUE THREAD

**Issue by ianstormtaylor** [felixfbecker/node-sql-template-strings#53]
It seems like the "API Documentation" link leads to this:

![image](https://user-images.githubusercontent.com/311752/30879356-084ea62c-a2b4-11e7-9a43-3c0e4d48d289.png)

Which is super confusing, because it seems to document a bunch of core node APIs and random other package APIs?

The only page that seems to be related to this library is [`Globals / SQLStatement / Class SQLStatement`](http://node-sql-template-strings.surge.sh/classes/sqlstatement.html) and even that page is not super helpful.

Might be better off just removing the documentation altogether, and just using a Readme.

**Comment by felixfbecker** [comment]
Yeah, in some update sometime typedoc it seems has started to include docs for typings. Does the same happen if you untick "Externals" in the top right? PR welcome

**Comment by ianstormtaylor** [comment]
Ah, unchecking "Externals" makes it exactly what I was expected, thank you!

**Comment by felixfbecker** [comment]
I think typedoc actually has a flag at build time like `--excludeExternals`, if you want to PR that

**Comment by felixfbecker** [comment]
Fixed
