### ISSUE TITLE
version 2.x is not compatible with github.com/felixge/node-mysql 

### ISSUE THREAD

**Issue by taojoe** [felixfbecker/node-sql-template-strings#6]
version 2.x use class 'get sql' to construct the sql string, this is not working with node-mysql. 

node-mysql use for(prop in sql), so the 'get sql' will not be called.

please see 
https://github.com/mysqljs/mysql/blob/master/lib/Connection.js#L50

**Comment by felixfbecker** [comment]
That shouldn't be an issue though.
```js
class X {
  get y() {
    return 'hello'
  }
}
const x = new X()
console.log('y' in x)
```

**Comment by felixfbecker** [comment]
Should be fixed in 0d660071d006591bcaac90938c518bd705c12161, could you please verify?

**Comment by taojoe** [comment]
Yes, it works.  Thanks.

**Comment by felixfbecker** [comment]
I will make a release on monday when Im home

**Comment by taojoe** [comment]
Could you make the release today?

**Comment by felixfbecker** [comment]
Sorry, I had no internet access the whole weekend. Released

**Comment by taojoe** [comment]
Thanks.
