### ISSUE TITLE
append function avoid null will be better.

### ISSUE THREAD

**Issue by taojoe** [felixfbecker/node-sql-template-strings#8]
hi Felix,

the new append function, accept string type, if check the parameter is better. when i pass undefined as parameter. the sql will be 'xxundefined'.

so please check the parameter before line 29, skip null/undefined will be good.

line 29 ,
  this.strings[this.strings.length - 1] += statement

**Comment by felixfbecker** [comment]
So you would like passing `undefined` or `null` to simply ignore the whole call? Could you post a code snippet where that would make sense and not be a bug?

The function signature is defined pretty clearly [here](https://github.com/felixfbecker/node-sql-template-strings/blob/master/index.d.ts#L19), don't know if I want to make the whole parameter optional, which would then turn the function into a noop.

**Comment by taojoe** [comment]
I extend this library with a 'merge' function, which takes more than one parameter, merge SQL into 1 SQL. The 'merge' function comes with version 1.x, when you upgrade to 2.x, I want to use append instead of 'merge'.

and the 'merge' function add space between sql part automatically.

`
var where;
    if(keyword){
        where=SQL`where phone like ${'%'+keyword+'%'}`;
    }
    var [{total}]=await mysql.query(SQL.merge(SQL`select count(*) as total from .user`, where));
    var list=await mysql.query(SQL.merge(SQL`SELECT * from .user `, where, SQL`limit 10 offset ${offset}`));
   // or the line above would be 
  var list=await mysql.query(SQL`SELECT * from .user `.append(where).append(SQL`limit 10 offset ${offset}`));
`

**Comment by felixfbecker** [comment]
I do it like this:
```ts
const query = SQL`SELECT * from user`;
if (keyword) {
  query.append(SQL` WHERE phone LIKE ${'%' + keyword + '%'}`);
}
query.append(SQL` LIMIT 10 OFFSET ${offset}`)
const list = await mysql.query(query);`
```

**Comment by taojoe** [comment]
if the code as below?   less variable name is better, isn't it?

```
var [{total}]=await mysql.query(SQL`select count(*) as total from .user`.append(where));
var list=await mysql.query(SQL`SELECT * from .user `.append(where).append(SQL`limit 10 offset ${offset}`));   
```

**Comment by felixfbecker** [comment]
You still have to declare and define `where` conditionally though, so you are not really saving variables. Of course this reads a bit nicer. I'm just thinking about wether this is a breaking change or not.

**Comment by taojoe** [comment]
I think this is not a breaking change.
